spring.application.name=igirepay

server.port=8080

# Show useful startup info
logging.level.com.igirepay=INFO

## Pretty-print JSON responses
#spring.jackson.serialization.indent-output=true
#spring.jackson.serialization.write-dates-as-timestamps=false